### ISSUE TITLE
Error: plot_results.py 

### ISSUE THREAD

**Issue by Nemophilist98** [ZhuYaoHui1998/SWformer-VO#2]
hi, Thank you for your work! I had a problem with the evaluation, reporting an error in the plot_results.py file:      

File “/home/doujiarui/SWformer-VO/plot_results.py”, line 102, in recover_trajectory_and_poses
    with open(os.path.join(”. /26.txt")) as f.
FileNotFoundError: [Errno 2] No such file or directory: '. /26.txt'

The trajectory generates the result .npy file, may I ask how to generate the txt format?

**Comment by ZhuYaoHui1998** [comment]
Hello, are you using KITTI data or custom data, if it is KITTI data, modify the 102 lines of the py file and the corresponding serial number of the KITTI data For example, 26 is modified to 00 01 02 03.txt

**Comment by Nemophilist98** [comment]
Thank you very much！

**Comment by Nemophilist98** [comment]
Dear authors, the SWformer-VO2 model failed to converge during my training. The parameters I set are as follows (referring to the paper):

![1732802057430](https://github.com/user-attachments/assets/dae24817-5678-4d35-8061-895d7ee8cd60)



```
args = {
        "data_dir": "data",
        "bsize": 8,  # batch size
        "val_split": 0.1,  # percentage to use as validation data
        "window_size": 2,  # number of frames in window
        "overlap": 1,  # number of frames overlapped between windows
        "optimizer": "Adam",  # optimizer [Adam, SGD, Adagrad, RAdam]
        "lr": 1e-5,  # learning rate
        "momentum": 0.9,  # SGD momentum
        "weight_decay": 1e-4,  # SGD momentum
        "epoch": 100,  # train iters each timestep
    	"weighted_loss": None,  # float to weight angles in loss function
      	"pretrained_ViT": False,  # load weights from pre-trained ViT
        "checkpoint_path": "checkpoints/1128",  # path to save checkpoint
        "checkpoint":None,  # checkpoint
    }

    # tiny  - patch_size=16, embed_dim=192, depth=12, num_heads=3
    # small - patch_size=16, embed_dim=384, depth=12, num_heads=6
    # base  - patch_size=16, embed_dim=768, depth=12, num_heads=12
    model_params = {
        "dim": 192,
        "image_size": (448, 678),  #(192, 640),  448 678 224 678
        "patch_size": 7,
        "attention_type": 'divided_space_time',  # ['divided_space_time', 'space_only','joint_space_time', 'time_only']
        "num_frames": args["window_size"],
        "sw_windows_size":8,
        "num_classes": 6 * (args["window_size"] - 1),  # 6 DoF for each frame
        "depth": 28,
        "heads": 28,
        "sw_depth": [12,8,8],
        "sw_num_heads":[12,12,12],
        "dim_head": 64,
        "attn_dropout": 0.1,
        "ff_dropout": 0.1,
        "time_only": False,
    }
```

Could you please give me some suggestions?

**Comment by xc-bnu** [comment]
> Hello, are you using KITTI data or custom data, if it is KITTI data, modify the 102 lines of the py file and the corresponding serial number of the KITTI data For example, 26 is modified to 00 01 02 03.txt

Are "00 01 02 03.txt" represented the ground truth? if so, I believe it's inappropriate to use it for plotting the predicted trajectory. We should not rely on ground truth data for this purpose.

**Comment by Nemophilist98** [comment]
> > Hello, are you using KITTI data or custom data, if it is KITTI data, modify the 102 lines of the py file and the corresponding serial number of the KITTI data For example, 26 is modified to 00 01 02 03.txt
> 
> Are "00 01 02 03.txt" represented the ground truth? if so, I believe it's inappropriate to use it for plotting the predicted trajectory. We should not rely on ground truth data for this purpose.

I used the plot_results.py file provided by TSformer.
